### ISSUE TITLE
Model is not present in libraby

### ISSUE THREAD

**Issue by pratikghanwat7** [ptarau/sumbert#1]
Thank you so much for this code.
I am facing an error while executing it.
I tried to change model to remi/bertabs-finetuned-cnndm-extractive-abstractive-summarization but still faced errors.

`
Traceback (most recent call last):
  File "/content/sumbert/sumbert/summarize.py", line 33, in <module>
    model = BertAbs.from_pretrained("bertabs-finetuned-cnndm")
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_utils.py", line 587, in from_pretrained
    **kwargs,
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_utils.py", line 201, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_utils.py", line 252, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'bertabs-finetuned-cnndm'. Make sure that:

- 'bertabs-finetuned-cnndm' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'bertabs-finetuned-cnndm' is the correct path to a directory containing a config.json file
`
How to fix this, or suggest  me a way to use "remi/bertabs-finetuned-cnndm-extractive-abstractive-summarization" mode.

Thanks in advance

**Comment by harshithbelagur** [comment]
Hey,

Open the run_summarization.py and replace "bertabs-finetuned-cnndm" with "remi/bertabs-finetuned-cnndm-extractive-abstractive-summarization".

Ensure that the name is in quotes and the line looks like this -
model = BertAbs.from_pretrained("remi/bertabs-finetuned-cnndm-extractive-abstractive-summarization")

I just ran it and it works perfectly fine!

**Comment by pratikghanwat7** [comment]
@harshithbelagur thank you so much for your suggestion. It worked for me as well.
@ptarau Thank you so much for such a great handy library.
